#!/usr/bin/env python3
# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
#
# Parse a rawprogram XML file generated by qcom-ptool. Search for first
# <program> element with provided label. Print its filename attribute,
# stripped of a leading "../" if present.
#
# Returns "none" if no such element found.
#
# Usage:  get-rawprogram-filename.py <label> <rawprogram0.xml>
#
# Example:
#   $ python3 get-rawprogram-filename.py rootfs rawprogram0.xml
#   disk-ufs.img2

import sys

from rawprogram import program_filename

if len(sys.argv) != 3:
    print(f"Usage: {sys.argv[0]} <label> <rawprogram0.xml>", file=sys.stderr)
    sys.exit(1)

label, xml_file = sys.argv[1], sys.argv[2]

filename = program_filename(xml_file, label)
print(filename if filename is not None else "none")
