# Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
# SPDX-License-Identifier: BSD-3-Clause
#
# Helpers for rawprogram XML files generated by qcom-ptool.

import defusedxml.ElementTree as ET


def program_filename(xml_file, label):
    """Return the filename of the first <program> element with label.

    Leading "../" path components are stripped. Returns None if no such
    element is found.
    """
    root = ET.parse(xml_file).getroot()
    e = root.find(f".//program[@label='{label}']")
    if e is None:
        return None

    filename = e.get("filename")
    # Strip any leading ../ path components
    while filename.startswith("../"):
        filename = filename[3:]
    return filename
