name: Build on push to branch

on:
  push:
    branches: [main]

# implicitely set all other permissions to none
permissions:
  checks: write # lava-test.yml
  contents: read # debos.yml lava-schema-check.yml lava-test.yml
  packages: read # lava-test.yml
  pull-requests: write # lava-test.yml

jobs:
  build-daily:
    strategy:
      fail-fast: false
      matrix:
        suite: [trixie, forky]
        kernelpackage: [linux-image-6.16.7-qcom1++, linux-image-arm64]
        exclude:
          - suite: trixie
            kernelpackage: linux-image-arm64
          - suite: forky
            kernelpackage: linux-image-6.16.7-qcom1++
    uses: ./.github/workflows/debos.yml
    with:
      suite: ${{ matrix.suite }}
      kernelpackage: ${{ matrix.kernelpackage }}
  schema-check:
    uses: ./.github/workflows/lava-schema-check.yml
  test:
    uses: ./.github/workflows/lava-test.yml
    needs: [build-daily, schema-check]
    secrets: inherit
    with:
      url: ${{ needs.build-daily.outputs.artifacts_url }}
