name: Build on PR

on:
  pull_request:

# implicitely set all other permissions to none
permissions:
  checks: write # lava-test.yml
  contents: read # debos.yml lava-schema-check.yml lava-test.yml
  packages: read # lava-test.yml
  pull-requests: write # lava-test.yml

jobs:
  event-file:
    name: "Upload event file"
    runs-on: ubuntu-latest
    steps:
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Event File
        path: ${{ github.event_path }}

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: debian
            suite: trixie
            # the package name will be passed to APT which interprets the
            # trailing plus sign in the package name as a request to install
            # the package, so use two plus signs
            kernelpackage: linux-image-6.16.7-qcom1++
          - distro: debian
            suite: forky
            kernelpackage: linux-image-arm64
          - distro: ubuntu
            suite: noble
            kernelpackage: linux-image-qcom
          - distro: ubuntu
            suite: resolute
            kernelpackage: linux-image-generic
    uses: ./.github/workflows/debos.yml
    with:
      suite: ${{ matrix.suite }}
      distro: ${{ matrix.distro }}
      kernelpackage: ${{ matrix.kernelpackage }}
  schema-check:
    uses: ./.github/workflows/lava-schema-check.yml
